### ISSUE TITLE
flutter: Add Splash Screen

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FreshNest#143]
## Issue:

When we open the app, it directly opens without any splash screen. It would be nice to have a splash screen with the application's logo on a white background(because currently we only support light mode).

**Comment by Mithilesh-create** [comment]
Please assign this issue to me . I would like to work on this issue.

**Comment by R0gue-one** [comment]
Hey I would like to work on this

**Comment by Sandesh-03** [comment]
hey , please assign this issue to me

**Comment by AmanNegi** [comment]
@R0gue-one Feel free to get started, let me know if you have some issues setting up.

@Sandesh-03 Feel free to come back we will be adding more issues soon!

**Comment by R0gue-one** [comment]
Hey @Sandesh-03 Bro what is your problem? this Issue was assigned to me why did you decide to work on this. This was a first issue and if you already a flutter developer why work on first issues. I thought I would learn flutter with this and also help this repo. I had to spend hours trying to get android studio setup on my new system now all the time I spent on learning is now  feels useless thanks to you. And you have been doing it for all the issues in this repo @AmanNegi even told you to work on other issues that are not assigned still you worked on this.

And it's not only this repo I have tried to contribute to 3 repos this week and even though it was assigned to me somebody else like you with hundreds of contributions did it few hours or minutes before me. 

Really sorry @AmanNegi for crying in your issues but I feel really annoyed since I started contributing to open source last week as whenever I try to do something new some "try-hard" will ruin it. I would have also added animations (infact I was going to ask if I should) but now there is no point in trying to learn it as it has already been done.

**Comment by AmanNegi** [comment]
Sorry @R0gue-one, I didn't notice this. Thanks for bringing this to my notice. You can continue to work on your PR.

**Comment by Sandesh-03** [comment]
Sorry @R0gue-one.

**Comment by R0gue-one** [comment]
Thanks for assigning me this issue @AmanNegi and sorry for the rant there (I think i needed some sleep). 

I was wondering if you could tell what font you use for your tagline so that I can update that.
Also should I add animations to the splash screen or keep it static ?

**Comment by AmanNegi** [comment]
Fixed via #149.

**Comment by R0gue-one** [comment]
@Sandesh-03 Sorry for lashing out at you the other day it was nothing personal was just annoyed by it happening to me since I started
